#    '||    ||'     |      ..|'''.|  '||'   ..|'''.| '||''|.   ..|''||   '|| '||'  '|' '||''''|  '||''|.   '||''''|  '||''|.
#     |||  |||     |||    .|'     '   ||  .|'     '   ||   || .|'    ||   '|. '|.  .'   ||  .     ||   ||   ||  .     ||   ||
#     |'|..'||    |  ||   ||    ....  ||  ||          ||...|' ||      ||   ||  ||  |    ||''|     ||''|'    ||''|     ||    ||
#     | '|' ||   .''''|.  '|.    ||   ||  '|.      .  ||      '|.     ||    ||| |||     ||        ||   |.   ||        ||    ||
#    .|. | .||. .|.  .||.  ''|...'|  .||.  ''|....'  .||.      ''|...|'      |   |     .||.....| .||.  '|' .||.....| .||...|'

# RainbowMonitor 彩虹监察
# 感谢使用 妙控动力 MagicPowered 插件。
# 心中所想事皆成，一路前行俱坦途。
# 东风夜放花千树，更吹落，星如雨。

# 拥有检查豁免的玩家，如果没有则删掉示例 "MIMIGZK"，需要保留 "-"
Exempt:
  - MIMIGZK

# 在哪些世界启用检查?
World:
  # 启用监察的世界: 世界在监察日志中的名字
  world: "主世界"
  world_nether: "下界"
  world_the_end: "末地"

# 在检测到超出限制的物品时，是否向指定玩家发送消息
SendInfo:
  state: true
  # 发送提示的玩家，如果没有则删掉示例 "MIMIGZK"，需要保留 "-"
  Player:
    - MIMIGZK

# 容器的 GUI 识别
ChestGui:
  # 识别后的名字
  随身背包:
    # 识别关键字，容器 GUI 的 Title 包含这个表中的词，则会使用识别后的名字在日志中记录
    - "随身背包"
  宠物背包:
    - "宠物背包"
  末影箱:
    - "末影箱"

# 需要检查的物品
ItemsToCheck:
  # 这是物品的唯一标识符，严格禁止重复，允许中文
  Item1:
    # 物品的材质，注意大写，这是精准匹配
    Material: PAPER
    # 物品的自定义名称，这是模糊匹配
    Name: 银票
    # 物品的描述，这是模糊匹配，但是对于单行，是精准匹配
    Lore:
      - "手持物品右键以兑换"
    # 物品允许的数量，超过此数量将会触发报告
    Amount: 10
  Item2:
    # 不配置的变量值不会检查
    Material: DRAGON_EGG
    Amount: 1